# Generated by Django 5.2.3 on 2025-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teacher.subject'),
        ),
    ]
