# Generated by Django 5.2.3 on 2025-06-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
    ]
